import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Issar Manknojiya | Full Stack Engineer</title>
        <meta name="viewport" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    </div>
  ) 
}