import Head from 'next/head';
import Image from 'next/image';
import Navbar from '../components/Navbar';
import Main from '../components/Main'; 

export default function Home() {
    return (
        <div>
            <Head className='flex min-h-screen flex-col bg-white'>
                <title key="title">Issar Manknojiya | Software Engineer</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
        <Navbar/> {/* Navbar component */}  
        <Main /> {/* Main component */}


        </div>
    )
}