import Image from "next/image";
import Navbar from "../components/Navbar";
import Head from "next/head";
import Main from "../components/Main";

export default function Home() {
  return (
    <div>
        <Head>
            <title key="title">Issar Manknojiya | Software Engineer</title>
            <meta name="description" content="Generated by create next app"/>
            <link rel="icon" href="/favicon.ico"/>
        </Head>
    <Navbar/> {/* Navbar component */}  
    <Main /> {/* Main component */}


    </div>
  )
}
